### ISSUE TITLE
docs.rs failing to compile dependent crate

### ISSUE THREAD

**Issue by spadarian** [georust/gdal#240]
Hello everyone. I hope you are having a good start to the year.

I'm having problems compiling the docs for my crate ([map-engine](https://crates.io/crates/map-engine)) probably because docs.rs' build system doesn't have GDAL installed.

I saw that you guys have a custom [build script](https://github.com/georust/gdal/blob/master/gdal-sys/build.rs#L65) that mentions a similar (?) problem. I was hoping that docs.rs would execute that and that everything would work :smile:

I also noticed that many of the crates that depend on gdal (not as a development dependency) have the same problem.

Do you have any recommendations on how to deal with this?

For future reference, I also created an issue on their repo: https://github.com/rust-lang/docs.rs/issues/1591

Thanks

**Comment by lnicola** [comment]
Looks like we're taking [this](https://github.com/georust/gdal/blob/v0.11.0/build.rs#L8) branch in the `gdal` (not `gdal-sys`) build script.

**Comment by lnicola** [comment]
@spadarian can you add

```toml
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
```

to your manifest?

**Comment by spadarian** [comment]
I will give that a try tomorrow.

Is there a way of checking if that works locally? I guess I can use their docker container...

Just to confirm... not `rustc-args = ["--cfg", "docsrs"]` like you have in [your Cargo.toml](https://github.com/georust/gdal/blob/master/Cargo.toml#L40)?

**Comment by rmanoka** [comment]
I also have the same problem in [`rasters`](https://github.com/AspecScire/rasters.rs/blob/master/Cargo.toml) crate.  I have included the `[package.metadata.docs.rs]` section, but the build still errors out.

The previous version of the crate (which used gdal 0.7.2) did build successfully: https://docs.rs/crate/rasters/0.6.2 .  Upgrading to latest, broke docs.

**Comment by rmanoka** [comment]
I seem to have added `rustc-args = [...]`, which worked in previous versions of the `rasters` crate (that uses gdal 0.7.2).
However, I tried locally (as explained using [docs.rs github](https://github.com/rust-lang/docs.rs#getting-started)) using `rustdoc-args = [...]` and it still fails.   

Intersetingly, even the previous version that did build successfully on docs.rs now fails when tried locally.  It suggests that this may be a bug in the docs.rs build process.

**Comment by spadarian** [comment]
Apparently, the guys from docs.rs have reported a bug in cargo, which is still blocked on https://github.com/rust-lang/cargo/issues/10206

**Comment by rmanoka** [comment]
The cargo issue above seems to be fixed now;  should it work now?

**Comment by spadarian** [comment]
I tried locally and it still fails...

**Comment by jdroenner** [comment]
i think we had that issue before...  Then it was caused by docs.rs but it might be something different this time

**Comment by rmanoka** [comment]
The cargo issue is fixed but docs.rs may also need to fix things (ref. https://github.com/rust-lang/docs.rs/issues/1580 , https://github.com/rust-lang/docs.rs/issues/1591).

**Comment by pka** [comment]
Builds are still failing (https://docs.rs/crate/geozero/0.9.5-beta1/builds/597082)

**Comment by rmanoka** [comment]
I noticed this fix in `proc-macro2` crate that has a similar problem.  Would it work for us?
https://github.com/dtolnay/proc-macro2/pull/310/files

**Comment by spadarian** [comment]
It wouldn't work. The compiler would try to compile both branches of the if statement, failing to find `gdal_sys::GDALVersionInfo`.

**Comment by rmanoka** [comment]
@spadarian @pka can you check your gdal-dependent crates and verify the docs do build?  I checked [rasters.rs](https://github.com/AspecScire/rasters.rs) locally and it builds;  it doesn't even seem to need the `rustc-args` configuration anymore.

**Comment by pka** [comment]
docs.rs build for geozero is working again, thanks!

**Comment by rmanoka** [comment]
Great!  Closing this as completed.
